#!/bin/bash
set -e

DEPENDENCIES=("markdownlint" "spellchecker" "write-good")
source $(dirname $0)/.util.sh


markdown_files=()
while IFS= read -r file; do
    markdown_files+=("$file")
done < <(
    find . -type f -name "*.md" #\
    # ! -name 'CODE_OF_CONDUCT.md'
)

markdown_command_fmts=(
    "markdownlint %s"
    "spellchecker -q --files %s"
    "write-good --no-illusion --no-tooWordy %s"
)

for cmd_fmt in "${markdown_command_fmts[@]}"; do
    for path in "${markdown_files[@]}"; do
        set +e
        cmd=$(printf "$cmd_fmt" "$path")
        if ! eval "$cmd"; then
            error "$cmd"
        else
            pass "$cmd"
        fi
        set -e
    done
done
