name: ci
on:
  push:
    branches:
      - main
jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          npm install -g markdownlint-cli write-good spellchecker-cli
      - name: make
        run: make
  deploy:
    needs: make
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install mkdocs mkdocs-material
      - name: Deploy to gh-pages branch
        run: mkdocs gh-deploy --force --clean --verbose
